name: Auto Recommand

on: push
#  schedule:
# #   #Update Every Monday 00:00
# #   - cron: "0 0 * * 1"
#     - cron: "0 0/1 * * *"


jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
        
      - name: Packaging
        run:|
            cd SJAlgorithm\
            mvn package
        
      - name: Run Recommand System
        run:|
            cd SJAlgorithm\
            java -jar target/SJAlgorithm-1.0-SNAPSHOT.jar ${{secrets.SECRET_TOKEN}}
        
#       - name: Compile
#         run: javac SJAlgorithm.java
        
#       - name: Run
#         run: java SJAlgorithm
