name: Auto Recommand

on:
  schedule:
    #Update Every Sunday 00:00 (UTC Time)
    - cron: "0 15 * * 6"


jobs:
  build:
    runs-on: ubuntu-latest
    env:
      working-directory: ./SJAlgorithmBot
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Package Clean
        run: mvn clean
        working-directory: ${{env.working-directory}}

      - name: Packaging
        run:  mvn package
        working-directory: ${{env.working-directory}}
        
      - name: Run Recommand System
        run:  java -jar target/SJAlgorithmBot-1.0-SNAPSHOT.jar ${{secrets.SECRET_TOKEN}}
        working-directory: ${{env.working-directory}}
