name: Auto Recommand

on: push
#  schedule:
# #   #Update Every Monday 00:00
# #   - cron: "0 0 * * 1"
#     - cron: "0 0/1 * * *"


jobs:
  build:
    runs-on: ubuntu-latest
    env:
      working-directory: ./SJAlgorithmBot
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: ls -al
        run: ls -al
        working-directory: ${{env.working-directory}}

      - name: Check Linux JDK Version
        run: mvn -verison

      - name: Packaging
        run:  mvn package
        working-directory: ${{env.working-directory}}
        
      - name: Run Recommand System
        run:  java -jar target/SJAlgorithm-1.0-SNAPSHOT.jar ${{secrets.SECRET_TOKEN}}
        working-directory: ${{env.working-directory}}
        
#       - name: Compile
#         run: javac SJAlgorithm.java
        
#       - name: Run
#         run: java SJAlgorithm
